Vagrant.configure("2") do |config|

  config.vm.box = "generic/ubuntu2004"
  config.vm.synced_folder "../../", "/home/vagrant/gotcp"
  config.vm.provision :shell, :path => "../setup.sh"

  config.vm.network "private_network", ip: "172.20.0.2"

end